import type { ResourceDefinition } from '../../types';

/**
 * Resource definitions. Chained resources matter: break the input and the
 * whole chain starves two days later, which is exactly the legible cascade
 * the simulation exists to produce.
 */
export const RESOURCES: Record<string, ResourceDefinition> = {
  water: {
    id: 'water',
    name: 'Spring Water',
    category: 'survival',
    icon: 'droplet',
    description:
      'Snowmelt off the Tellmar Range, carried down the Grand Aqueduct. Everything in Valenreach is downstream of this.',
    basePrice: 4,
    unit: 'barrel',
    baseOutput: 440,
    storageCapacity: 4000,
    spoilageRate: 0,
    parCover: 8,
    perCapitaDemand: 0.02,
    seasonProfile: 'water',
    elasticity: 1.9,
    sourceFacility: 'grand_aqueduct',
  },
  grain: {
    id: 'grain',
    name: 'Barley & Wheat',
    category: 'survival',
    icon: 'wheat',
    description: 'The Goldfields harvest. Stored in the great silos, counted in days of survival.',
    basePrice: 9,
    unit: 'sack',
    baseOutput: 880,
    storageCapacity: 8000,
    spoilageRate: 0.004,
    parCover: 12,
    perCapitaDemand: 0.006,
    seasonProfile: 'crop',
    elasticity: 1.7,
    sourceFacility: 'goldfield_silos',
  },
  bread: {
    id: 'bread',
    name: 'Hearthbread',
    category: 'survival',
    icon: 'croissant',
    description: 'Dense, dark, and the difference between a quiet district and a burning one.',
    basePrice: 14,
    unit: 'loaf',
    baseOutput: 420,
    storageCapacity: 1500,
    spoilageRate: 0.15,
    parCover: 1.5,
    perCapitaDemand: 0.02,
    seasonProfile: 'processed',
    elasticity: 1.6,
    inputs: [{ resourceId: 'grain', amount: 1 }],
    sourceFacility: 'common_bakeries',
  },
  fish: {
    id: 'fish',
    name: 'River Trout',
    category: 'food',
    icon: 'fish',
    description: 'Hauled from the Wharfs before dawn. Cheap when the nets are good.',
    basePrice: 11,
    unit: 'catch',
    baseOutput: 180,
    storageCapacity: 900,
    spoilageRate: 0.22,
    parCover: 1.5,
    perCapitaDemand: 0.008,
    seasonProfile: 'harvest',
    elasticity: 1.2,
    sourceFacility: 'harbor_fishery',
  },
  fruit: {
    id: 'fruit',
    name: 'Suncrest Apples',
    category: 'food',
    icon: 'apple',
    description: 'Thornwood orchard fruit. A luxury in the Ashes, an afterthought on the Hill.',
    basePrice: 8,
    unit: 'basket',
    baseOutput: 115,
    storageCapacity: 700,
    spoilageRate: 0.12,
    parCover: 3,
    perCapitaDemand: 0.005,
    seasonProfile: 'crop',
    elasticity: 0.9,
    sourceFacility: 'thornwood_orchards',
  },
  herbs: {
    id: 'herbs',
    name: 'Wild Herbs',
    category: 'medicine',
    icon: 'leaf',
    description: 'Feverfew, bitterroot, silverleaf. Lyra knows which ones are lying about what they do.',
    basePrice: 16,
    unit: 'bundle',
    baseOutput: 190,
    storageCapacity: 700,
    spoilageRate: 0.06,
    parCover: 2,
    perCapitaDemand: 0.002,
    seasonProfile: 'industry',
    elasticity: 1.1,
    sourceFacility: 'thornwood_herbary',
  },
  medicine: {
    id: 'medicine',
    name: 'Elixir of Vigor',
    category: 'medicine',
    icon: 'flask-round',
    description: 'Elena distills it in small batches. Demand for it is a measure of how bad things are.',
    basePrice: 45,
    unit: 'vial',
    baseOutput: 36,
    storageCapacity: 400,
    spoilageRate: 0.01,
    parCover: 8,
    perCapitaDemand: 0.0015,
    seasonProfile: 'processed',
    elasticity: 1.8,
    inputs: [{ resourceId: 'herbs', amount: 2 }],
    sourceFacility: 'apothecary_hall',
  },
  cloth: {
    id: 'cloth',
    name: 'Woolen Cloth',
    category: 'goods',
    icon: 'shirt',
    description: 'Weaverlane runs on it. So does half the guild vote.',
    basePrice: 22,
    unit: 'bolt',
    baseOutput: 95,
    storageCapacity: 900,
    spoilageRate: 0,
    parCover: 8,
    perCapitaDemand: 0.004,
    seasonProfile: 'processed',
    elasticity: 0.8,
    sourceFacility: 'weaverlane_looms',
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Bog Iron',
    category: 'material',
    icon: 'mountain',
    description: 'Hauled up from the Emberworks shafts, heavy and cheap until it is neither.',
    basePrice: 13,
    unit: 'load',
    baseOutput: 210,
    storageCapacity: 1400,
    spoilageRate: 0,
    parCover: 8,
    perCapitaDemand: 0.002,
    seasonProfile: 'industry',
    elasticity: 0.7,
    sourceFacility: 'emberworks_mines',
  },
  tools: {
    id: 'tools',
    name: 'Forged Tools',
    category: 'goods',
    icon: 'hammer',
    description: "Torvin's work. Farms stop without them, and nobody notices until they do.",
    basePrice: 38,
    unit: 'set',
    baseOutput: 62,
    storageCapacity: 600,
    spoilageRate: 0,
    parCover: 8,
    perCapitaDemand: 0.002,
    seasonProfile: 'processed',
    elasticity: 0.9,
    inputs: [{ resourceId: 'iron_ore', amount: 2 }],
    sourceFacility: 'great_foundry',
  },
  arms: {
    id: 'arms',
    name: 'Arms & Mail',
    category: 'military',
    icon: 'swords',
    description: 'Spears, mail, and the bills for both. The garrison is always short.',
    basePrice: 85,
    unit: 'kit',
    baseOutput: 20,
    storageCapacity: 320,
    spoilageRate: 0,
    parCover: 10,
    perCapitaDemand: 0.0008,
    seasonProfile: 'processed',
    elasticity: 1.4,
    inputs: [
      { resourceId: 'iron_ore', amount: 2 },
      { resourceId: 'tools', amount: 1 },
    ],
    sourceFacility: 'great_foundry',
  },
  luxuries: {
    id: 'luxuries',
    name: 'Court Luxuries',
    category: 'luxury',
    icon: 'gem',
    description: 'Silk, spice, coloured glass. Nobody needs it; the nobility will riot without it.',
    basePrice: 120,
    unit: 'crate',
    baseOutput: 24,
    storageCapacity: 300,
    spoilageRate: 0,
    parCover: 8,
    perCapitaDemand: 0.0006,
    seasonProfile: 'industry',
    elasticity: 0.5,
    sourceFacility: 'bourse_imports',
  },
  contraband: {
    id: 'contraband',
    name: 'Contraband',
    category: 'illicit',
    icon: 'skull',
    description: 'Untaxed, unnamed, and moving through the catacombs tonight regardless of the law.',
    basePrice: 95,
    unit: 'parcel',
    baseOutput: 20,
    storageCapacity: 250,
    spoilageRate: 0,
    parCover: 8,
    perCapitaDemand: 0.0005,
    seasonProfile: 'industry',
    elasticity: 1.5,
    sourceFacility: 'catacomb_market',
  },
};

export const RESOURCE_LIST: ResourceDefinition[] = Object.values(RESOURCES);

export function getResource(id: string): ResourceDefinition | undefined {
  return RESOURCES[id];
}
