import type { PerkDefinition } from '../../types';

/**
 * Bond perks — the systemic payoff of a relationship, and the reason bonding
 * is a progression mechanic rather than a side gallery.
 *
 * Every perk here is read by an engine stage. None of them are flavor text.
 * When adding one, find the stage that will consume it in the same change.
 */
export const BOND_PERKS: PerkDefinition[] = [
  /* --- Caren: the granaries --------------------------------------- */
  {
    id: 'caren_warm',
    name: "The Honest Count",
    description: 'Caren shows you the true granary reserves, not the figure the court is given.',
    npcId: 'caren',
    tier: 'Warm',
    kind: 'unlock',
    value: 1,
    target: 'granary_truth',
  },
  {
    id: 'caren_close',
    name: 'The Quiet Reserve',
    description: 'She keeps a reserve nobody has written down. Famine events hit the kingdom 40% less hard.',
    npcId: 'caren',
    tier: 'Close',
    kind: 'crisis_severity',
    value: -0.4,
    target: 'famine',
  },
  {
    id: 'caren_devoted',
    name: "The Harvest's Share",
    description: 'You may draw three days of grain cover from the reserve each season, without a writ.',
    npcId: 'caren',
    tier: 'Devoted',
    kind: 'production_multiplier',
    value: 0.15,
    target: 'grain',
  },

  /* --- Mira: the aqueduct ----------------------------------------- */
  {
    id: 'mira_warm',
    name: 'Scored Seals',
    description: 'Mira warns you before sabotage at Springhead becomes a shortage.',
    npcId: 'mira',
    tier: 'Warm',
    kind: 'unlock',
    value: 1,
    target: 'sabotage_warning',
  },
  {
    id: 'mira_close',
    name: 'Priority of Flow',
    description: 'You choose which district the cisterns serve first. Water production rises 20%.',
    npcId: 'mira',
    tier: 'Close',
    kind: 'production_multiplier',
    value: 0.2,
    target: 'water',
  },
  {
    id: 'mira_devoted',
    name: 'The Melt Ledger',
    description: 'Drought events are halved. She has been planning for the next one since the last one.',
    npcId: 'mira',
    tier: 'Devoted',
    kind: 'crisis_severity',
    value: -0.5,
    target: 'drought',
  },

  /* --- Rin: the exchange ------------------------------------------ */
  {
    id: 'rin_warm',
    name: 'Before the Bell',
    description: 'You see the true spread before the floor opens.',
    npcId: 'rin',
    tier: 'Warm',
    kind: 'unlock',
    value: 1,
    target: 'market_preview',
  },
  {
    id: 'rin_close',
    name: "A Factor's Courtesy",
    description: 'Rin quotes you at cost. Buy at 0.9x, sell at 1.1x.',
    npcId: 'rin',
    tier: 'Close',
    kind: 'market_buy_multiplier',
    value: 0.9,
  },
  {
    id: 'rin_close_sell',
    name: "A Factor's Courtesy (Sale)",
    description: 'Your sales clear at a premium on the Bourse floor.',
    npcId: 'rin',
    tier: 'Close',
    kind: 'market_sell_multiplier',
    value: 1.1,
  },
  {
    id: 'rin_devoted',
    name: 'Exclusive Contracts',
    description: 'Contracts written in your name only. Buy at 0.8x, sell at 1.15x.',
    npcId: 'rin',
    tier: 'Devoted',
    kind: 'market_buy_multiplier',
    value: 0.8,
  },
  {
    id: 'rin_devoted_sell',
    name: 'Exclusive Contracts (Sale)',
    description: 'The consortium takes your stock first and pays for the privilege.',
    npcId: 'rin',
    tier: 'Devoted',
    kind: 'market_sell_multiplier',
    value: 1.15,
  },

  /* --- Vesper: the syndicate -------------------------------------- */
  {
    id: 'vesper_warm',
    name: 'The Syndicate Looks Away',
    description: 'Bounty accrues at half the usual rate. Somebody is losing your name from the ledgers.',
    npcId: 'vesper',
    tier: 'Warm',
    kind: 'bounty_rate',
    value: 0.5,
  },
  {
    id: 'vesper_close',
    name: "Member's Rates",
    description: 'The catacomb market prices you as one of its own.',
    npcId: 'vesper',
    tier: 'Close',
    kind: 'market_buy_multiplier',
    value: 0.85,
    target: 'contraband',
  },
  {
    id: 'vesper_devoted',
    name: 'The Dossier',
    description: 'Vesper will build a blackmail file on any figure at court, once asked.',
    npcId: 'vesper',
    tier: 'Devoted',
    kind: 'unlock',
    value: 1,
    target: 'blackmail',
  },

  /* --- Beatrix: the church ---------------------------------------- */
  {
    id: 'beatrix_warm',
    name: 'Confession',
    description: 'Minor bounty is absolved at the cathedral, quietly and without record.',
    npcId: 'beatrix',
    tier: 'Warm',
    kind: 'unlock',
    value: 1,
    target: 'absolution',
  },
  {
    id: 'beatrix_close',
    name: 'The Pulpit Inclines',
    description: 'Church opinion of you rises by 1 each day while your standing with them holds.',
    npcId: 'beatrix',
    tier: 'Close',
    kind: 'faction_daily',
    value: 1,
    target: 'church',
  },
  {
    id: 'beatrix_devoted',
    name: 'Pulpit Endorsement',
    description: 'She speaks for one of your decrees from the cathedral steps. Commons opinion +15 on it.',
    npcId: 'beatrix',
    tier: 'Devoted',
    kind: 'unlock',
    value: 15,
    target: 'endorsement',
  },
  {
    id: 'beatrix_sworn',
    name: 'Anointment',
    description: 'Sol names you. The Anointed route to the throne opens.',
    npcId: 'beatrix',
    tier: 'Sworn',
    kind: 'unlock',
    value: 1,
    target: 'route_anointed',
  },

  /* --- Claire: the ninth company ---------------------------------- */
  {
    id: 'claire_warm',
    name: 'Escort',
    description: 'The ninth walks your routes. Ambush events no longer fire.',
    npcId: 'claire',
    tier: 'Warm',
    kind: 'unlock',
    value: 1,
    target: 'no_ambush',
  },
  {
    id: 'claire_close',
    name: 'Drill Partner',
    description: 'Claire trains you personally. +2 Might.',
    npcId: 'claire',
    tier: 'Close',
    kind: 'attribute_bonus',
    value: 2,
    target: 'might',
  },
  {
    id: 'claire_devoted',
    name: 'The Ninth Answers',
    description: 'One garrison intervention per crisis, without a writ and without asking Valerius.',
    npcId: 'claire',
    tier: 'Devoted',
    kind: 'crisis_severity',
    value: -0.3,
  },

  /* --- Lyra: the thornwood ---------------------------------------- */
  {
    id: 'lyra_warm',
    name: 'The Good Verges',
    description: 'She shows you where the herbs actually grow. Herb yields +20%.',
    npcId: 'lyra',
    tier: 'Warm',
    kind: 'production_multiplier',
    value: 0.2,
    target: 'herbs',
  },
  {
    id: 'lyra_close',
    name: "The Herbalist's Standing Gift",
    description: 'A vial arrives every week whether you asked or not.',
    npcId: 'lyra',
    tier: 'Close',
    kind: 'unlock',
    value: 1,
    target: 'weekly_medicine',
  },

  /* --- Elena: the apothecary -------------------------------------- */
  {
    id: 'elena_warm',
    name: 'Attentive Care',
    description: 'Illness recovery is twice as fast, for you and for anyone you bring her.',
    npcId: 'elena',
    tier: 'Warm',
    kind: 'illness_recovery',
    value: 2,
  },
  {
    id: 'elena_close',
    name: 'Plague Protocol',
    description: 'Plague crises kill half as many. She has had three years to write the procedure.',
    npcId: 'elena',
    tier: 'Close',
    kind: 'crisis_severity',
    value: -0.5,
    target: 'plague',
  },
  {
    id: 'elena_devoted',
    name: 'The Research Subject',
    description: 'Her regimen permanently raises one attribute by 3. She is delighted by the data.',
    npcId: 'elena',
    tier: 'Devoted',
    kind: 'attribute_bonus',
    value: 3,
    target: 'cunning',
  },

  /* --- Sylvie: the guilds ----------------------------------------- */
  {
    id: 'sylvie_warm',
    name: 'Guild Gossip',
    description: 'You see what the guilds intend before the council does.',
    npcId: 'sylvie',
    tier: 'Warm',
    kind: 'unlock',
    value: 1,
    target: 'faction_intent',
  },
  {
    id: 'sylvie_close',
    name: 'One Loom, One Vote',
    description: 'Weaverlane votes with you in council.',
    npcId: 'sylvie',
    tier: 'Close',
    kind: 'unlock',
    value: 1,
    target: 'guild_vote',
  },
  {
    id: 'sylvie_devoted',
    name: 'At Cost',
    description: 'Cloth and luxuries at the guild rate rather than the floor rate.',
    npcId: 'sylvie',
    tier: 'Devoted',
    kind: 'market_buy_multiplier',
    value: 0.75,
    target: 'cloth',
  },

  /* --- Seraphine: the household ----------------------------------- */
  {
    id: 'seraphine_warm',
    name: 'The Household Schedule',
    description: 'You know where everyone at court will be, and when.',
    npcId: 'seraphine',
    tier: 'Warm',
    kind: 'unlock',
    value: 1,
    target: 'court_schedule',
  },
  {
    id: 'seraphine_close',
    name: 'Received Without Rank',
    description: 'The Crown Quarter admits you regardless of estate.',
    npcId: 'seraphine',
    tier: 'Close',
    kind: 'unlock',
    value: 1,
    target: 'court_access',
  },
  {
    id: 'seraphine_devoted',
    name: 'Royal Favor',
    description: 'One decree per season passes unopposed. She signs for the king; she has for months.',
    npcId: 'seraphine',
    tier: 'Devoted',
    kind: 'unlock',
    value: 1,
    target: 'decree_unopposed',
  },
  {
    id: 'seraphine_sworn',
    name: 'Legitimacy',
    description: 'The succession papers can be made to name you. The Heir route opens.',
    npcId: 'seraphine',
    tier: 'Sworn',
    kind: 'unlock',
    value: 1,
    target: 'route_heir',
  },

  /* --- Elare: the archive ----------------------------------------- */
  {
    id: 'elare_warm',
    name: 'Records Lookup',
    description: 'Elare will find you anything on anyone in the archive.',
    npcId: 'elare',
    tier: 'Warm',
    kind: 'unlock',
    value: 1,
    target: 'records',
  },
  {
    id: 'elare_close',
    name: 'The Genealogies',
    description: 'Every house has a line it would rather you did not trace. She has traced them all.',
    npcId: 'elare',
    tier: 'Close',
    kind: 'unlock',
    value: 1,
    target: 'genealogy',
  },
  {
    id: 'elare_devoted',
    name: 'The Eleven Days',
    description: 'The volumes cut out of the Drought record. She copied them before the blade came.',
    npcId: 'elare',
    tier: 'Devoted',
    kind: 'unlock',
    value: 1,
    target: 'drought_archive',
  },
];

export const PERKS_BY_ID: Record<string, PerkDefinition> = Object.fromEntries(
  BOND_PERKS.map((p) => [p.id, p]),
);

/** Perks a companion grants, in tier order. */
export function perksForNpc(npcId: string): PerkDefinition[] {
  return BOND_PERKS.filter((p) => p.npcId === npcId);
}
