import type { JobDefinition } from '../../types';

/**
 * Work available to the player. Each job costs energy, pays copper, advances
 * a career track, and moves the supervising NPC's affection — so choosing
 * work is simultaneously an economic, career, and relationship decision.
 */
export const JOBS: JobDefinition[] = [
  /* --- Unskilled: available from day one, to anyone ---------------- */
  {
    id: 'haul_water',
    title: 'Haul Water from the Cisterns',
    description:
      'Buckets up the Springhead stair, from the fourth bell to noon. Your shoulders will tell you about it tomorrow.',
    facility: 'grand_aqueduct',
    supervisorNpcId: 'mira',
    energyCost: 18,
    requires: {},
    supervisorAffection: 3,
    rewards: {
      attributes: { might: 0.25 },
      copper: 26,
      xp: 12,
      standingPoints: 6,
      kingdom: { welfare: 1 },
      items: [{ resourceId: 'water', amount: 2 }],
    },
  },
  {
    id: 'mend_nets',
    title: 'Mend Nets on the Wharfs',
    description: 'Cold rope, colder water, and Bran talking the entire time. The talk is the better half of the wage.',
    facility: 'harbor_fishery',
    supervisorNpcId: 'bran',
    energyCost: 16,
    requires: {},
    supervisorAffection: 3,
    rewards: {
      attributes: { might: 0.2, charm: 0.1 },
      copper: 22,
      xp: 10,
      standingPoints: 5,
      items: [{ resourceId: 'fish', amount: 2 }],
    },
  },
  {
    id: 'weed_goldfields',
    title: 'Clear Thistle from the Goldfields',
    description: 'Bent double between the rows until the light goes. Caren works the row beside you and does not complain.',
    facility: 'goldfield_silos',
    supervisorNpcId: 'caren',
    energyCost: 20,
    requires: {},
    supervisorAffection: 4,
    rewards: {
      attributes: { might: 0.3 },
      copper: 28,
      xp: 12,
      standingPoints: 6,
      kingdom: { welfare: 1 },
      items: [{ resourceId: 'grain', amount: 2 }],
    },
  },
  {
    id: 'forage_herbs',
    title: 'Forage the Thornwood Verges',
    description: 'Lyra names each one twice — once properly, once the way the old women say it. Only one of the two is safe.',
    facility: 'thornwood_herbary',
    supervisorNpcId: 'lyra',
    energyCost: 15,
    requires: {},
    track: 'scholar',
    supervisorAffection: 4,
    rewards: {
      attributes: { cunning: 0.3, piety: 0.1 },
      copper: 20,
      xp: 12,
      standingPoints: 5,
      careerXp: [{ track: 'scholar', amount: 10 }],
      items: [{ resourceId: 'herbs', amount: 2 }],
    },
  },

  /* --- Merchant track --------------------------------------------- */
  {
    id: 'run_stall',
    title: 'Run a Stall at the Bourse',
    description: 'Rin gives you a pitch, a float, and ninety seconds of advice. The advice is worth more than the float.',
    facility: 'bourse_imports',
    supervisorNpcId: 'rin',
    energyCost: 20,
    track: 'merchant',
    requires: { estate: 'Peasant' },
    supervisorAffection: 4,
    rewards: {
      attributes: { cunning: 0.35, charm: 0.2 },
      copper: 48,
      xp: 16,
      standingPoints: 8,
      guildMarks: 2,
      careerXp: [{ track: 'merchant', amount: 22 }],
      factions: [{ factionId: 'guilds', opinion: 1 }],
    },
  },
  {
    id: 'broker_contracts',
    title: 'Broker Caravan Contracts',
    description: 'Four factors, three languages, and one clause that nobody wants read aloud. You read it aloud.',
    facility: 'bourse_imports',
    supervisorNpcId: 'silas',
    energyCost: 26,
    track: 'merchant',
    requires: { estate: 'Villager', career: [{ track: 'merchant', minRank: 2 }] },
    supervisorAffection: 3,
    rewards: {
      attributes: { cunning: 0.5, charm: 0.3, authority: 0.15 },
      copper: 140,
      xp: 30,
      standingPoints: 14,
      guildMarks: 6,
      careerXp: [{ track: 'merchant', amount: 55 }],
      factions: [{ factionId: 'guilds', opinion: 2 }],
    },
  },

  /* --- Martial track ---------------------------------------------- */
  {
    id: 'drill_with_ninth',
    title: 'Drill with the Ninth Company',
    description: 'Claire runs you into the ground and then tells you, sincerely, that you did well. Both parts are true.',
    facility: 'garrison_barracks',
    supervisorNpcId: 'claire',
    energyCost: 24,
    track: 'martial',
    requires: { estate: 'Peasant' },
    supervisorAffection: 5,
    rewards: {
      attributes: { might: 0.4, authority: 0.15 },
      copper: 38,
      xp: 18,
      standingPoints: 8,
      guildMarks: 2,
      careerXp: [{ track: 'martial', amount: 24 }],
      factions: [{ factionId: 'military', opinion: 1 }],
    },
  },
  {
    id: 'wall_patrol',
    title: 'Walk the Rampart Patrol',
    description: 'Six hours of nothing, and the one hour that makes the other six worth paying for.',
    facility: 'garrison_walls',
    supervisorNpcId: 'valerius',
    energyCost: 28,
    track: 'martial',
    requires: { estate: 'Villager', career: [{ track: 'martial', minRank: 2 }] },
    supervisorAffection: 2,
    rewards: {
      attributes: { might: 0.5, authority: 0.3 },
      copper: 95,
      xp: 28,
      standingPoints: 13,
      guildMarks: 5,
      careerXp: [{ track: 'martial', amount: 50 }],
      kingdom: { security: 1 },
      factions: [{ factionId: 'military', opinion: 2 }],
    },
  },

  /* --- Clergy track ----------------------------------------------- */
  {
    id: 'almshouse_service',
    title: 'Serve at the Almshouse Door',
    description: 'Four hundred people, one ladle, and Beatrix watching how you speak to the last of them.',
    facility: 'cathedral_almshouse',
    supervisorNpcId: 'beatrix',
    energyCost: 18,
    track: 'clergy',
    requires: {},
    supervisorAffection: 5,
    rewards: {
      attributes: { piety: 0.35, charm: 0.2 },
      copper: 18,
      xp: 16,
      standingPoints: 10,
      guildMarks: 2,
      careerXp: [{ track: 'clergy', amount: 22 }],
      kingdom: { welfare: 1, piety: 1 },
      factions: [
        { factionId: 'church', opinion: 2 },
        { factionId: 'refugees', opinion: 1 },
      ],
    },
  },
  {
    id: 'dawn_devotions',
    title: 'Lead the Dawn Devotions',
    description: 'You speak, and three hundred people decide whether to believe you. Beatrix does not help.',
    facility: 'cathedral_almshouse',
    supervisorNpcId: 'beatrix',
    energyCost: 22,
    track: 'clergy',
    requires: { estate: 'Villager', career: [{ track: 'clergy', minRank: 2 }] },
    supervisorAffection: 4,
    rewards: {
      attributes: { piety: 0.5, charm: 0.3, authority: 0.15 },
      copper: 70,
      xp: 26,
      standingPoints: 15,
      guildMarks: 5,
      careerXp: [{ track: 'clergy', amount: 50 }],
      kingdom: { piety: 2 },
      factions: [{ factionId: 'church', opinion: 3 }],
    },
  },

  /* --- Court track ------------------------------------------------ */
  {
    id: 'copy_records',
    title: 'Copy Records in the Archive',
    description: 'Elare gives you the dull volumes. Somewhere in the dull volumes is why she keeps letting you back in.',
    facility: 'royal_archive',
    supervisorNpcId: 'elare',
    energyCost: 14,
    track: 'court',
    requires: { estate: 'Peasant' },
    supervisorAffection: 5,
    rewards: {
      attributes: { authority: 0.35, cunning: 0.2 },
      copper: 32,
      xp: 16,
      standingPoints: 7,
      guildMarks: 2,
      careerXp: [
        { track: 'court', amount: 20 },
        { track: 'scholar', amount: 10 },
      ],
      factions: [{ factionId: 'crown', opinion: 1 }],
      kingdom: { literacy: 1 },
    },
  },

  /* --- Shadow track ----------------------------------------------- */
  {
    id: 'run_parcel',
    title: 'Run a Parcel through the Catacombs',
    description:
      'Vesper does not tell you what is in it. That is the arrangement, and the arrangement pays four times a day at the cisterns.',
    facility: 'catacomb_market',
    supervisorNpcId: 'vesper',
    energyCost: 20,
    track: 'shadow',
    requires: {},
    supervisorAffection: 4,
    rewards: {
      attributes: { cunning: 0.4, might: 0.1 },
      copper: 88,
      xp: 16,
      standingPoints: 3,
      bounty: 6,
      careerXp: [{ track: 'shadow', amount: 24 }],
      factions: [
        { factionId: 'syndicate', opinion: 3 },
        { factionId: 'crown', opinion: -1 },
      ],
    },
  },

  /* --- Craft --------------------------------------------------- */
  {
    id: 'work_the_looms',
    title: 'Work the Weaverlane Looms',
    description: 'Sylvie puts you on a loom to see whether you last the morning. Most do not.',
    facility: 'weaverlane_looms',
    supervisorNpcId: 'sylvie',
    energyCost: 19,
    requires: {},
    track: 'merchant',
    supervisorAffection: 4,
    rewards: {
      attributes: { charm: 0.25, cunning: 0.1 },
      copper: 34,
      xp: 13,
      standingPoints: 6,
      careerXp: [{ track: 'merchant', amount: 12 }],
      items: [{ resourceId: 'cloth', amount: 1 }],
    },
  },
  {
    id: 'foundry_shift',
    title: 'Take a Shift at the Great Foundry',
    description: 'Torvin says three words all morning and two of them are corrections. The third is "good".',
    facility: 'great_foundry',
    supervisorNpcId: 'torvin',
    energyCost: 26,
    requires: { estate: 'Peasant' },
    supervisorAffection: 3,
    rewards: {
      attributes: { might: 0.35 },
      copper: 52,
      xp: 18,
      standingPoints: 8,
      items: [{ resourceId: 'tools', amount: 1 }],
    },
  },
  {
    id: 'distill_tinctures',
    title: 'Distill Tinctures with Elena',
    description: 'She hands you a mask and does not explain why until after you have put it on.',
    facility: 'apothecary_hall',
    supervisorNpcId: 'elena',
    energyCost: 21,
    track: 'scholar',
    requires: { estate: 'Peasant' },
    supervisorAffection: 4,
    rewards: {
      attributes: { cunning: 0.4, piety: 0.15 },
      copper: 58,
      xp: 22,
      standingPoints: 9,
      guildMarks: 3,
      careerXp: [{ track: 'scholar', amount: 28 }],
      kingdom: { publicHealth: 1 },
      items: [{ resourceId: 'medicine', amount: 1 }],
    },
  },
];

export const JOBS_BY_ID: Record<string, JobDefinition> = Object.fromEntries(
  JOBS.map((job) => [job.id, job]),
);
